apiVersion: v1
kind: Secret
metadata:
  name: stockrush-secrets
  namespace: stockrush
type: Opaque
data:
  PRODUCT_DB_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9zdG9ja3J1c2hfcHJvZHVjdHM=
  ORDER_DB_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9zdG9ja3J1c2hfb3JkZXJz
  AUTH_DB_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9zdG9ja3J1c2hfYXV0aA==
  PASETO_SECRET_KEY: azQuc2VjcmV0LkNnSzBSZGNvREl5a2cxSGN3TkwtNElvdEFOU1J4ZGZsUWJ2ckZlUGx0WGZ2XzNPRTVUYUJPeEx6TTFVdFlZVU1LUGZ2UWJGMXFTa1AwWDdQWHNrUFFR
  PASETO_PUBLIC_KEY: azQucHVibGljLjdfOXpoT1UyZ1RzUzh6TlZMV0dGRENqMzcwR3hkYWtwRDlGLXoxN0pEMEU=
  GMAIL_USER: cHJhZGh1bW5kZXYyMkBnbWFpbC5jb20=
  GMAIL_APP_PASSWORD: eWV2emdyb2JiZGp1bmx5ZQ==