apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: stockrush-services
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - stockrush
  selector:
    matchLabels:
      monitor: "true"
  endpoints:
    - port: http
      path: /metrics
      interval: 15s